### PR TITLE
Adding a function to easily import a private key

### PR DESCRIPTION
**Pull request by Yuriicaezar**
**Added a function PrivateKey.ts to ./src/key/ that uses the RawKey function to import the private key.**
PrivateKey takes a string as an argument and turns it into an array needed by RawKey. The function also checks the private key for correctness, and can work with private keys both with and without the “0x” prefix. 

**I also made changes to index.ts to add a function to the list of available functions.**

### CODE REVIEW

**Comment by joon9823** [comment]
@Yuriicaezar I feel like adding the below method to already existing RawKey class seems better
what do you think?

```
  public static fromHex(key: string): RawKey {
    const hex = key.startsWith('0x') ? key.slice(2) : key
    if (hex.length !== 64) throw new Error('Invalid private key length')
    return new RawKey(Buffer.from(hex, 'hex'))
  }
```

if you agree, I will implement this and publish to npm

**Comment by Yuriicaezar** [comment]
@joon9823 Yes, I agree, it looks even better and simpler without overloading the code.

**Comment by joon9823** [comment]
https://github.com/initia-labs/initia.js/commit/5545f8edb56da6aee0881b70ff4e8f28070c58b4
already applied this change and published to npm as v0.2.0!
@Yuriicaezar feel free to close this pr :)

**Comment by Yuriicaezar** [comment]
@joon9823 thanks)

**Pull request closed without merging**
